version: '3'
services:
  db:
    ports:
      - 5432:5432
    env_file:
      - ./cognitus.env

  redis:
    ports:
      - 6379:6379

  algorithm_celery:
    env_file:
      - ./cognitus.env

  web:
    command: python manage.py runserver 0:8000
    ports:
      - 8000:8000
    env_file:
      - ./cognitus.env

  algorithm:
    command: flask run
    ports:
      - 5000:5000
    env_file:
      - ./cognitus.env
