version: '3'
services:
  db:
    image: postgres
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
  algorithm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
