version: '3'
services:
  db:
    environment:
      POSTGRES_USER: cognitus
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  web:
    command: python manage.py runserver 0:8000
    entrypoint: /code/docker/web/entrypoint.sh
    volumes:
      - ..:/code
    ports:
      - 8000:8000
  algorithm:
    command: python algorithm/app.py
    entrypoint: /code/docker/algorithm/entrypoint.sh
    volumes:
      - ..:/code
    ports:
      - 5000:5000
