version: '3'
services:
  db:
    image: postgres

  redis:
    image: redis

  algorithm_celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery worker -l info -A algorithm
    entrypoint: /code/docker/algorithm_celery/entrypoint.sh
    volumes:
      - ..:/code
    depends_on:
      - redis

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: /code/docker/web/entrypoint.sh
    volumes:
      - ..:/code
    depends_on:
      - db
      - algorithm_celery

  algorithm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: /code/docker/algorithm/entrypoint.sh
    volumes:
      - ..:/code
    depends_on:
      - db
      - algorithm_celery
